
-- AUTOMOTIVE SALES ANALYSIS 

-- 1. Display all customers who live in Frankfurt.
SELECT customer_id, first_name, last_name,city
FROM customers
WHERE city= 'Frankfurt';

-- 2. Display all vehicles with a list price greater than €50,000.
SELECT vehicle_id, brand, list_price FROM vehicles
WHERE list_price>50000
ORDER BY vehicle_id; 

-- 3. Show all orders that were paid using Finance.
SELECT order_id, payment_method
FROM orders
WHERE payment_method = 'Finance'; 

-- 4. Display all SUVs that use Diesel fuel.

SELECT vehicle_type, fuel_type
FROM vehicles
WHERE vehicle_type= 'SUV' AND fuel_type = 'Diesel'; 

-- 5. Find the total number of customers.

SELECT * FROM customers; 
SELECT COUNT(customer_id) 
FROM customers;

-- 6. Find the average age of all customers.
SELECT AVG(age) AS avg_age
FROM customers
;

-- 7. Find the minimum, maximum, and average vehicle list price.
SELECT MAX(list_price) AS min_price, 
MIN(list_price) AS max_price, AVG(list_price) AS avg_price
FROM vehicles;

-- 8. How many customers are there in each German state?
SELECT * FROM customers; 
SELECT COUNT(customer_id) AS num_customer, state
FROM customers 
GROUP BY state; 

-- 9. How many vehicles are available for each brand?
SELECT * FROM vehicles;
SELECT COUNT(vehicle_id) number_of_vehicles, brand
FROM vehicles
GROUP BY brand; 

-- 10. What is the average list price for each brand?
SELECT brand, AVG(list_price)
FROM vehicles
GROUP BY brand
ORDER BY Brand;

-- 11. Calculate the total number of orders for each dealer.

SELECT dealer_id, COUNT(order_id)
FROM orders
GROUP BY dealer_id; 

-- 12. Calculate the total revenue generated by each vehicle brand.

SELECT v.brand,
SUM(o.quantity* o.selling_price)
FROM vehicles v JOIN orders o
ON v.vehicle_id= o.vehicle_id
GROUP BY v.brand;
;

-- 13. Most frequently used payment method

SELECT payment_method, COUNT(payment_method)
FROM orders
GROUP BY payment_method
LIMIT 1;

-- 14. Calculate the average discount given for each vehicle brand.

SELECT v.brand, AVG(e.discount) AS avg_discount
FROM orders e 
JOIN vehicles v
ON 
	e.vehicle_id= v.vehicle_id
GROUP BY v.brand;

-- 15. SHOW customer name , vehicle brand, vehicle model, selling price, order date

SELECT c.first_name, c.last_name, o.order_date, o.selling_price,v.brand,v.model
FROM customers c
JOIN 
	orders o
ON 
	c.customer_id= o.customer_id
JOIN vehicles  v
ON o.vehicle_id=v.vehicle_id;

-- 16. Show every dealer and the number of orders they have received.

SELECT dealer_name, COUNT(order_id)
FROM dealers d 
JOIN orders o 
ON d.dealer_id=o.dealer_id
GROUP BY dealer_name;

-- 17. Find the total revenue generated by each dealer. DISPLAY dealer_name, city, total_revenue
 
SELECT o.dealer_id, d.dealer_name, d.city , SUM(o.selling_price) AS total_revenue
FROM dealers d
JOIN orders o
ON d.dealer_id= o.dealer_id
GROUP BY o.dealer_id
;

-- 18. Find the top 5 customers based on the total amount they have spent.

SELECT c.customer_id, c.first_name, c.last_name, SUM(o.selling_price) AS amount_spent
FROM customers c
JOIN orders o
ON
c.customer_id = o.customer_id
GROUP BY c.customer_id
ORDER BY amount_spent DESC
LIMIT 5; 

-- 19. Find the most popular vehicle model based on the number of orders.

SELECT v.model, COUNT(o.order_id) AS top_seller_model
FROM vehicles v
JOIN orders o
ON 
v.vehicle_id= o.vehicle_id
GROUP BY v.vehicle_id
ORDER BY top_seller_model DESC
LIMIT 1;

-- 20. Create a new column called customer_age_group. Classify customers as Under 30, 30-39, 40-49, 50+

SELECT CONCAT(first_name, ' ' ,last_name) AS customers_name,
CASE 
	WHEN age<30 THEN 'Young'
    WHEN age BETWEEN 30 AND 39 THEN 'MIDDLE AGED'
    WHEN age BETWEEN 40 AND 49 THEN 'TRUNING 50 SHORTLY'
    WHEN age>50 THEN 'OLD'
END AS customer_age_group
FROM customers
ORDER BY 1
;

-- 21. Create a new column called vehicle_price_category. Budget < €40,000 , Mid-range  €40,000–€59,999, Premium >= €60,000
SELECT * FROM vehicles; 

SELECT vehicle_id, brand, model,list_price, 
CASE
	WHEN list_price<40000 THEN 'BUDGET'
    WHEN list_price BETWEEN 40000 AND 59000 THEN 'MID-RANGE'
    WHEN list_price >= 60000 THEN 'PREMIUM'
END AS vehicle_price_category
FROM vehicles; 

-- 22. Find customers whose age is above the average customer age.
SELECT first_name,last_name, age 
FROM customers
WHERE age>
(SELECT AVG(age) FROM customers AS avg_age) 
; 
-- 23. Find vehicles whose list price is higher than the average vehicle list price.


SELECT vehicle_id, brand, model, list_price,
(SELECT AVG(list_price) FROM vehicles) AS avg_price
FROM vehicles
WHERE list_price>
(SELECT AVG(list_price) FROM vehicles)

;

-- 24. Find employees/customers who have spent more than the average customer spending.

SELECT
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    SUM(o.selling_price * o.quantity) AS total_spending
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name
HAVING SUM(o.selling_price * o.quantity) > (
    SELECT AVG(selling_price)
    FROM orders
)
ORDER BY total_spending DESC;

-- 25. Rank all vehicle models according to their total sales revenue. 

SELECT
    v.model,
    SUM(o.selling_price * o.quantity) AS total_revenue,
    RANK() OVER (
        ORDER BY SUM(o.selling_price * o.quantity) DESC
    ) AS revenue_rank
FROM vehicles v
JOIN orders o
    ON v.vehicle_id = o.vehicle_id
GROUP BY v.vehicle_id, v.model
ORDER BY revenue_rank;

-- 26. Rank vehicles within each brand based on their list price.


SELECT vehicle_id, brand, model,
RANK() OVER(PARTITION BY brand ORDER BY list_price DESC) AS price_rank
FROM vehicles;

-- 27. Find the highest-revenue vehicle model for each brand.

SELECT brand,model,total_revenue
FROM 
(SELECT 
v.brand, v.model,
SUM(o.selling_price) AS total_revenue,
RANK() OVER (PARTITION BY v.brand ORDER BY SUM(o.selling_price) DESC ) AS rn
FROM vehicles v
JOIN orders o
ON v.vehicle_id=o.vehicle_id
GROUP BY v.brand , v.model

) AS ranked
WHERE rn=1;


-- 28. For each customer order, calculate the difference between the order's selling price and the average selling price of all orders.

SELECT order_id, selling_price,
AVG(selling_price) OVER() AS avg_price,
selling_price-AVG(selling_price) OVER() AS difference_btw_price
FROM orders; 

-- 29. CREATE A RESULT CONTAINING dealer_name, total_orders, total_revenue,average_order_value,dealer_rank

SELECT d.dealer_id, d.dealer_name, COUNT(o.order_id), SUM(o.selling_price), 
AVG(o.selling_price) ,
RANK() OVER(ORDER BY SUM(o.selling_price) DESC) AS dealer_rank
FROM dealers d
JOIN orders o
ON
d.dealer_id= o.dealer_id
GROUP BY  d.dealer_id
ORDER BY dealer_rank; 

-- 30. "Which vehicle brands and models are performing best, and which dealerships are contributing the most revenue?"
-- Brand, Model, Number of Orders, Total Revenue, Average Selling Price, Rank Within Brand

SELECT
    brand,
    model,
    number_of_orders,
    total_revenue,
    average_selling_price,
    RANK() OVER (
        PARTITION BY brand
        ORDER BY total_revenue DESC
    ) AS rank_within_brand
FROM (
    SELECT
        v.brand,
        v.model,
        COUNT(o.order_id) AS number_of_orders,
        SUM(o.selling_price * o.quantity) AS total_revenue,
        AVG(o.selling_price) AS average_selling_price
    FROM vehicles v
    JOIN orders o
        ON v.vehicle_id = o.vehicle_id
    GROUP BY v.brand, v.vehicle_id, v.model
) AS model_summary
ORDER BY brand, rank_within_brand;

